security:
    encoders:
      App\Entity\User:
        algorithm: auto
    providers:
            databaseusers:
                entity:
                    class: App\Entity\User
                    property: username
                    # if you're using multiple entity managers
                    # manager_name: customer
    role_hierarchy:
            ROLE_ADMIN: ROLE_USER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: databaseusers
            form_login:
              login_path: login
              check_path: login
              default_target_path: indice
            logout:
              path: /logout
              target: indice

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/registro$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: /private/, roles: [ROLE_USER, ROLE_ADMIN] }
         - { path: /admin/, roles: ROLE_ADMIN }